### ISSUE TITLE
Music overlapping for some reason?

### ISSUE THREAD

**Issue by TonisGaming** [Booo3/red_money#11]
https://streamable.com/2t6h54

**Comment by Booo3** [comment]
@TonisGaming does it happen more then once?

**Comment by TonisGaming** [comment]
It happened twice,  in the same heist. No clue what triggered it

**Comment by Booo3** [comment]
Idk why it happens, i don't get that bug, but i changed when the music gets loaded in the last commit. Maybe that will fix it?

**Comment by TonisGaming** [comment]
Seems to be fixed
