### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by VirtRaider** [Booo3/red_money#20]
Hello,
When I try to load the mission it has an extremely long loading screen, followed by the player list loading percentage going from 0-13% multiple times and then crashing to desktop.

**Comment by VirtRaider** [comment]
Application has crashed: C++ exception
Could not load texture because IDirect3D9::CreateCubeTexture call failed.
Direct3D could not allocate sufficient memory to complete the call.

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlInitializeCriticalSectionAndSpinCount            
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlCaptureContext                                   


-------------------------------

Current thread: Renderer

-------------------------------

System information:
	Application version : 1.96.909
	CPU : Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2070 / nvldumd.dll[27.21.14.5206]
	Language : english
	Memory :     32687MB 296KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (Corsair VOID Wireless Gaming Dongle))

**Comment by Booo3** [comment]
It's a known issue, lower your texture quality and it should load.
