### ISSUE TITLE
Unistall cheats and you can play

### ISSUE THREAD

**Issue by HypermorphicGaming** [Booo3/red_money#21]
Pretty sure this is on me, but I want to play Red Money. I installed the map, and now it says that I need to unistall cheats. I don't have cheats, but I do use a few mods.

-Silent Assassin
-Create Empty Lobby
-Removable Mask
-uHUD Enemy Health and Info
-Secret Achievement Highlighter & Filter

Does one of these mods trigger it?

**Comment by Booo3** [comment]
Silent Assassin is a cheat
